const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),{load}=require('./data.cjs'),c=load(),standard=require('./fixtures/pre-companion-engine.js'),E=require('../engine.js');
let checks=0,builds=0,defaults=0;const changes=[];const equal=(a,b,msg)=>{checks++;assert.equal(JSON.stringify(a),JSON.stringify(b),msg);};
function validate(t,o,size){checks++;assert(Object.keys(o.bench).length<=size);assert(Object.keys(o.pen).length<=12-size);assert(Object.keys(o.rotation).length<=5);const all=[...Object.values(o.start),...Object.values(o.bench),...Object.values(o.rotation),...Object.values(o.pen)];const ids=all.map(n=>(t.hitters.find(h=>h.name===n)||t.pitchers.find(p=>p.name===n)).id);assert.equal(new Set(ids).size,ids.length);assert(ids.length<=26);if(o.pen.LONG)assert(E.longQualification(t,t.pitchers.find(p=>p.name===o.pen.LONG)).ok);}
for(const t0 of c.LL_DATA.teams){for(const scoped of [t0,...(c.LL_CITIES[t0.code]?.cities||[]).map(city=>standard.withCity(t0,city))])for(const bm of [false,true]){const t=bm?standard.withBM(scoped):scoped,a=standard.build(t,{});equal(E.build(t,{}),a,t.name+' default exact');equal(E.build(t,{rules:{bench_size:5}}),standard.build(t,{rules:{bench_size:5}}),t.name+' explicit Standard');defaults++;
for(const size of [5,6,7]){const o=E.build(t,{rules:{bench_size:size}});validate(t,o,size);builds++;if(!scoped.city&&!bm){assert.equal(Object.keys(o.bench).length,size,t.name+' bench size');assert.equal(Object.keys(o.pen).length,12-size,t.name+' pen size');assert.equal(Object.keys(o.rotation).length,5);if(size>5)changes.push({team:t0.key,benchSize:size,bullpenSize:12-size,benchAdded:Object.entries(o.bench).filter(([s])=>!a.bench[s]).map(([slot,name])=>({slot,name})),bullpenBefore:a.pen,bullpenAfter:o.pen,rotationChanged:JSON.stringify(o.rotation)!==JSON.stringify(a.rotation),startingNineChanged:JSON.stringify(o.start)!==JSON.stringify(a.start)});}
if(size>5&&o.bench.BAT2){const pinName=o.bench.BAT2,p=E.build(t,{rules:{bench_size:size},roster:{[pinName]:'BAT2'}});equal(p.bench.BAT2,pinName,'extra bench pin works');validate(t,p,size);const wrong=E.reviewPins(t,{rules:{bench_size:5},roster:{[pinName]:'BAT2'}});assert(wrong.warnings.some(w=>w.structural));}
const role=Object.values(o.pen)[0];if(role){const p=E.build(t,{rules:{bench_size:size},staff:{[role]:'CL'},acknowledged:[]});validate(t,p,size);}
}}}
equal(c.LL_DATA.teams.map(t=>t.hitters.map(h=>h.total)),load().LL_DATA.teams.map(t=>t.hitters.map(h=>h.total)),'APEX unmodified');
const result={passed:true,franchises:30,standardBuildsCompared:defaults,balancedBuildsChecked:builds,checks,standardRosterChanges:0,changes};console.log({passed:true,franchises:30,standardBuildsCompared:defaults,balancedBuildsChecked:builds,checks,standardRosterChanges:0});
